name: Add quote
description: Add a new quote or an additional quote for a specific time.
title: "[XX:XX] Add quote"
labels:
  - add-quote
body:
  - type: markdown
    attributes:
      value: "# Add quote"
  - type: input
    id: time
    attributes:
      label: Time
      description: Please update the title as well!
      placeholder: "04:00"
    validations:
      required: true
  - type: input
    id: book
    attributes:
      label: Book
      placeholder: "2666"
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      placeholder: Roberto Bolaño
    validations:
      required: true
  - type: textarea
    id: quote
    attributes:
      label: Quote text
      placeholder: The night before Albert Kessler arrived in Santa Teresa, at four in the morning, Sergio Gonzalez Rodriguez got a call from Azucena Esquivel Plata, reporter and PRI congresswoman.
    validations:
      required: true